pipeline {
    agent { label 'master' }

    environment {
        USER_CREDENTIALS = credentials('e641eb29-97c7-4000-86a2-f2c35072a7cc')
        VERSAO_GIT = '$(git rev-parse HEAD | cut -c 1-10)'
		VERSAO_GRADLE = '2.14'
    }
    stages {
        stage('GIT CLONE'){
            steps{
                git branch: 'master',
                    credentialsId: '095337cb-cf01-426b-a6fd-d6152e5b4932',
                    url: 'https://github.com/Infoglobo/devops.git'                   
            }
        }
        stage('DOCKER BUILD') {
            steps {
                sh "docker version"

                echo "### COMANDO DOCKER BUILD ###"
                sh "docker build -t imagem_gradle:temp ${WORKSPACE}/docker/gradle/"

                echo "### PERMISSAO PARA TFSSERVICE ###"
                sh "sudo chown -R tfsservice.suporte ${WORKSPACE}/docker/gradle/"
            }
        }
        stage('DOCKER TAG E PUSH'){
            steps{

                echo "### INCLUINDO TAG NO NOME DA IMAGEM ###"
                sh "docker tag imagem_gradle:temp renatoadsumus/gradle:${VERSAO_GRADLE}_$VERSAO_GIT"
                sh "docker tag imagem_gradle:temp renatoadsumus/gradle:${VERSAO_GRADLE}_latest"

                echo "### LOGIN DOCKERHUB ###"
                sh "docker login --username=${USER_CREDENTIALS_USR} --password=${USER_CREDENTIALS_PSW}"

                echo "### EXECUTANDO PUSH DA IMAGEM GERADA ###"
                sh "docker push renatoadsumus/gradle:${VERSAO_GRADLE}_$VERSAO_GIT"
                sh "docker push renatoadsumus/gradle:${VERSAO_GRADLE}_latest"

                echo "### VOLTANDO PERMISSAO PARA JENKINS ###"
                sh "sudo chown -R jenkins. ${WORKSPACE}/docker/gradle/"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
