pipeline {
    agent { label 'globo_extra_slave' }
    environment {
        USER_CREDENTIALS = credentials('e641eb29-97c7-4000-86a2-f2c35072a7cc')
        VERSAO_GIT = '$(git rev-parse HEAD | cut -c 1-10)'

    }
    
    stages {
        stage('Clone'){
            steps{
                git branch: 'master',
                    credentialsId: '095337cb-cf01-426b-a6fd-d6152e5b4932',
                    url: 'https://github.com/Infoglobo/devops.git'
            }
        }
        stage('Build') {
            steps {
                sh "echo ${VERSAO_GIT}"
                sh "docker build -t renatoadsumus/nodejs:6.11.5 $WORKSPACE/docker/node_js/"
            }
        }
        stage('Copy'){
            steps{
                sh "docker login --username=${USER_CREDENTIALS_USR} --password=${USER_CREDENTIALS_PSW}"
                sh "docker push renatoadsumus/nodejs:6.11.5"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}