pipeline {
    agent { label 'globo_extra_slave' }
    parameters {
        choice(
            choices: '4.5.2',
            description: '',
            name: 'VERSAO')
    }
    environment {
        USER_CREDENTIALS = credentials('e641eb29-97c7-4000-86a2-f2c35072a7cc')
        VERSAO_GIT = '$(git rev-parse HEAD | cut -c 1-10)'
        XML_PROJETO = 'testes/Funcionario-REST-soapui-project.xml'
        TEST_SUIT = 'SmokeTests'
        ENDPOINT_TESTES = 'http://apidsv'

    }
    stages {
        stage('GIT CLONE'){
            steps{
                git branch: 'master',
                    credentialsId: '095337cb-cf01-426b-a6fd-d6152e5b4932',
                    url: 'https://github.com/Infoglobo/devops.git'                   
            }
        }
        stage('DOCKER BUILD') {
            steps {
                sh "docker version"

                echo "### COMANDO DOCKER BUILD ###"
                sh "docker build -t renatoadsumus/soapui:${VERSAO}_${VERSAO_GIT} ${WORKSPACE}/docker/soapui/${VERSAO}"
            }
        }
        stage('DOCKER RUN') {
            steps{
                echo "### PERMISSAO PARA GO ###"
                sh "sudo chown -R go.go ${WORKSPACE}/docker/soapui/${VERSAO}"
                sh "sudo chmod 777 ${WORKSPACE}/docker/soapui/${VERSAO}"

                echo "### COMANDO DOCKER RUN ###"
                sh "docker run --rm -v ${WORKSPACE}/docker/soapui/${VERSAO}:/pasta_projeto renatoadsumus/soapui:${VERSAO}_${VERSAO_GIT} /pasta_projeto/$XML_PROJETO -s '$TEST_SUIT' -j -f /pasta_projeto -r -e $ENDPOINT_TESTES"
            }
        }
        stage('DOCKER TAG E PUSH'){
            steps{
                echo "### INCLUINDO TAG NO NOME DA IMAGEM ###"
                sh "docker tag renatoadsumus/soapui:${VERSAO}_${VERSAO_GIT} renatoadsumus/soapui:${VERSAO}_latest"

                echo "### LOGIN DOCKERHUB ###"
                sh "docker login --username=${USER_CREDENTIALS_USR} --password=${USER_CREDENTIALS_PSW}"

                echo "### EXECUTANDO PUSH DA IMAGEM GERADA ###"
                sh "docker push renatoadsumus/soapui:${VERSAO}_${VERSAO_GIT}"
                sh "docker push renatoadsumus/soapui:${VERSAO}_latest"

                echo "### VOLTANDO PERMISSAO PARA JENKINS ###"
                sh "sudo chown -R jenkins. ${WORKSPACE}/docker/soapui/${VERSAO}"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}